# Generated by Django 3.0.8 on 2021-11-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lunch", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="order", name="dish"),
        migrations.AddField(
            model_name="menu",
            name="option_four",
            field=models.CharField(default="Dish 4", max_length=250),
        ),
        migrations.AddField(
            model_name="menu",
            name="option_one",
            field=models.CharField(default="Dish 1", max_length=250),
        ),
        migrations.AddField(
            model_name="menu",
            name="option_three",
            field=models.CharField(default="Dish 3", max_length=250),
        ),
        migrations.AddField(
            model_name="menu",
            name="option_two",
            field=models.CharField(default="Dish 2", max_length=250),
        ),
        migrations.AddField(
            model_name="order",
            name="menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="lunch.Menu"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selection",
            field=models.CharField(default="No selection", max_length=50),
        ),
        migrations.DeleteModel(name="Dish"),
    ]
