# Generated by Django 3.0.8 on 2021-11-17 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0003_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="lunch.Menu"
            ),
        ),
    ]
