# Generated by Django 3.0.8 on 2021-11-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0005_employee_slack_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(default="NOT_SENT", max_length=10),
        ),
    ]
