# Generated by Django 3.0.8 on 2021-11-18 03:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0006_auto_20211117_0636"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="date",
            field=models.DateField(default=datetime.date(2021, 11, 18), unique=True),
        ),
    ]
