# Generated by Django 3.0.8 on 2021-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0008_auto_20211118_0327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
